plugins {
    id 'java'
}

group = 'ru.otus.anatoly'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // implementation ("ch.qos.logback:logback-classic:1.5.12")

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.3'

    testImplementation platform('org.junit:junit-bom:6.1.3')
    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.3'
    testImplementation 'org.assertj:assertj-core:3.27.7'
}

test {
    useJUnitPlatform()
}


